# Course settings
course:
  link: https://github.com/programoergosum/programacion-en-python-con-raspberry-pi
  title: Programación en Python con Raspberry Pi
  description: Curso para formación del profesorado en Programación y Robótica con Raspberry Pi.
  author: 
    name: Miguel Ángel Abellán
    link: https://migueabellan.github.io
  center: IES Miguel de Cervantes, Murcia

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

exclude:
  - docker-compose.yml
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
