version: '3'

services:

  jekyll:
    image: jekyll/jekyll:latest
    container_name: programacion-en-python-con-raspberry-pi
    command: jekyll serve --watch --incremental
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll